SHOW DATABASES;

CREATE DATABASE PROJETO_OF;

USE PROJETO_OF;

/*TABELAS*/

CREATE TABLE CLIENTE(
IDCLIENTE INT UNIQUE AUTO_INCREMENT,
NOME VARCHAR(60) NOT NULL,
SEXO ENUM("M","F") NOT NULL
);

CREATE TABLE TELEFONE(
IDTELEFONE INT UNIQUE AUTO_INCREMENT,
TIPO ENUM("CEL","RES","COM") NOT NULL,
TELEFONE VARCHAR(11) NOT NULL,
ID_CLIENTE INT NOT NULL
);

CREATE TABLE CARRO (
IDCARRO INT UNIQUE AUTO_INCREMENT,
CHASSE VARCHAR(100),
MODELO VARCHAR(100),
ID_MARCA INT NOT NULL,
ID_CLIENTE INT NOT NULL
);

CREATE TABLE TINTA(
IDCOR INT UNIQUE AUTO_INCREMENT,
COR VARCHAR(10)
);

CREATE TABLE MARCA(
IDMARCA INT UNIQUE AUTO_INCREMENT,
MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO_TINTA(
IDCARRO INT,
IDCOR INT
);

/*VERIFICANDO CRIAÇÃO DAS TABELAS*/

SHOW DATABASES;
SHOW TABLES;

/*CHAVES*/

/*CHAVES PRIMARIAS*/

ALTER TABLE CLIENTE
ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (IDCLIENTE);

ALTER TABLE TELEFONE
ADD CONSTRAINT PK_TELEFONE
PRIMARY KEY (IDTELEFONE);

ALTER TABLE CARRO
ADD CONSTRAINT PK_CARRO
PRIMARY KEY (IDCARRO);

ALTER TABLE MARCA
ADD CONSTRAINT PK_MARCA
PRIMARY KEY (IDMARCA);

ALTER TABLE TINTA
ADD CONSTRAINT PK_TINTA
PRIMARY KEY (IDCOR);

ALTER TABLE CARRO_TINTA
ADD CONSTRAINT PK_CARRO_TINTA
PRIMARY KEY (IDCOR,IDCARRO);

/*CHAVES ESTRANGEIRAS*/

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE (IDCLIENTE);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE (IDCLIENTE);

ALTER TABLE CARRO
ADD CONSTRAINT FK_MARCA_CARRO
FOREIGN KEY (ID_MARCA)
REFERENCES MARCA (IDMARCA);

ALTER TABLE CARRO_TINTA
ADD CONSTRAINT FK_CARRO_CARROTINTA
FOREIGN KEY (IDCARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO_TINTA
ADD CONSTRAINT FK_TINTA_CARROTINTA
FOREIGN KEY (IDCOR)
REFERENCES TINTA(IDCOR);

/*VERIFICANDO REGRAS E TABELAS*/

SHOW TABLES;

SHOW CREATE TABLE CLIENTE;
SHOW CREATE TABLE TELEFONE;
SHOW CREATE TABLE CARRO;
SHOW CREATE TABLE TINTA;
SHOW CREATE TABLE MARCA;
SHOW CREATE TABLE CARRO_TINTA;

/*INSERT 10 REGISTROS*/
