CREATE DATABASE PROJETO;

SHOW DATABASES;

USE PROJETO;

CREATE TABLE CURSOS (
IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
HORAS INT(3) NOT NULL,
VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO CURSOS VALUES (NULL, 'JAVA', 30, 500.00);
INSERT INTO CURSOS VALUES (NULL, 'FUNDAMENTOS DE BANCO DE DADOS', 40, 700.00);

SELECT * FROM CURSOS;

DELIMITER $

STATUS

CREATE PROCEDURE CAD_CURSOS(P_NOME VARCHAR(30), 
							P_HORAS INT(3), 
							P_VALOR FLOAT(10,2))
BEGIN
	INSERT INTO CURSOS VALUES (NULL, P_NOME,P_HORAS,P_VALOR);
END
$

DELIMITER ;

STATUS

CALL CAD_CURSOS ('BI SQL SERVER',35,3000.00);
CALL CAD_CURSOS ('POWER BI',20,1000.00);
CALL CAD_CURSOS ('TABLEAU',30,1200.00);

SELECT * FROM CURSOS;

/*CRIAR UMA PROCEDURE PARA CONSULTAR CURSOS*/

DELIMITER $

STATUS

CREATE PROCEDURE CON_CURSOS()
BEGIN
SELECT * FROM CURSOS;
END
$

DELIMITER ;

STATUS

CALL CON_CURSOS();