/*CRIAR BANCO DE DADOS LIVRARIA*/
CREATE DATABASE LIVRARIA;

/*CONECTAR AO BANCO DE DADOS*/
USE LIVRARIA;

/*CRIAR TABELA LIVROS*/
CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(100),
	NOME_AUTOR VARCHAR(100),
	SEXO_AUTOR CHAR(1),
	NUMERO_DE_PAGINAS INT,
	NOME_DA_EDITORA VARCHAR(100),
	VALOR FLOAT(5,2),
	UF_EDITORA CHAR(2),
	ANO_PUBLICACAO CHAR(4) 
);

/*INSERIR REGISTROS*/

INSERT INTO LIVROS 
VALUES
('Cavaleiro Real','Ana Claudia','F',465,'Atlas',49.9,'RJ','2009'),
('SQL para leigos','João Nunes','M',450,'Addison',98,'SP','2018'),
('Receitas Caseiras','Celia Tavares','F',210,'Atlas',45,'RJ','2008'),
('Pessoas Efetivas','Eduardo Santos','M',390,'Beta',78.99,'RJ','2018'),
('Habitos Saudaveis','Eduardo Santos','M',630,'Beta',150.98,'RJ','2019'),
('A Casa Marrom','Hermes Macedo','M',250,'Bubba',60,'MG','2016'),
('Estacio Querido','Geraldo Francisco','M',310,'Insigna',100,'ES','2015'),
('Pra sempre amigas','Leda Silva','F',510,'Insigna',78.98,'ES','2011'),
('Copas inesqueciveis','Marco Alcantara','M',200,'Larson',130.98,'RS','2018'),
('O poder da mente','Clara Mafra','F',120,'Continental',56.58,'SP','2017');

/*EXERCICIO 1 - TRAZER TODOS OS DADOS*/
SELECT * FROM LIVROS;

/*EXERCICIO 2 - TRAZER O NOME DO LIVRO E O NOME DA EDITORA*/
SELECT NOME_LIVRO, NOME_DA_EDITORA FROM LIVROS;

/*EXERCICIO 3 - TRAZER O NOME DO LIVRO E A UF DOS LIVROS, PUBLICADOS POR AUTORES DO SEXO MASCULINO*/
SELECT NOME_LIVRO, UF_EDITORA FROM LIVROS
WHERE SEXO_AUTOR = 'M';

/*EXERCICIO 4 - TRAZER O NOME DO LIVRO E O NUMERO DE PAGINAS DOS LIVROS, PUBLICADOS POR AUTORES DO SEXO FEMININO*/
SELECT NOME_LIVRO, NUMERO_DE_PAGINAS FROM LIVROS
WHERE SEXO_AUTOR = 'F';

/*EXERCICIO 5 - TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO*/
SELECT VALOR FROM LIVROS
WHERE UF_EDITORA = 'SP';

/*EXERCICIO 6 - TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO*/
SELECT NOME_AUTOR FROM LIVROS
WHERE (SEXO_AUTOR = 'M' AND (UF_EDITORA = 'RJ' OR UF_EDITORA = 'SP'));