/*EXERCICIO DE ESTUDO DE TRIGGERS*/

/*CRIAÇÃO DE DATABASE*/

CREATE DATABASE AULA40;

USE AULA40;

/*CRIAÇÃO DE TABELA*/

CREATE TABLE USUARIO(
IDUSUARIO INT AUTO_INCREMENT,
NOME VARCHAR(30),
LOGIN VARCHAR(30),
SENHA VARCHAR(100)
);

-- TABELA DE BACKUP
CREATE TABLE BKP_USUARIO(
IDBACKPU INT AUTO_INCREMENT,
IDUSUARIO INT,
NOME VARCHAR(30),
LOGIN VARCHAR(30)
);

/*CHAVES PRIMARIA*/

ALTER TABLE USUARIO
ADD CONSTRAINT PK_USUARIO
PRIMARY KEY (IDUSUARIO);

ALTER TABLE BKP_USUARIO
ADD CONSTRAINT PK_BKPUSUARIO
PRIMARY KEY (IDBACKPU);

/*CRIANDO A TRIGGERS*/

DELIMITE #

-- QUANDO APAGADO OS REGISTROS DA TABELA USUARIO,
-- PEGA OS VALORES ANTIGOS DA TABELA USUARIO E PASSA PARA TABELA BKP_USUARIO

CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
INSERT INTO BKP_USUARIO 
VALUES
(NULL, OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);
END
#

--CONCEITO DE NEW E OLD

DELIMITER ;

/*INSERT - USUARIOS*/

INSERT INTO USUARIO 
VALUES 
(NULL,"ANDRADE","ANDRADE2009,""),


