/*COMUNICAÇÃO ENTRE BANCOS DE DADO*/

/*CRIAÇÃO DO BANCO DE DADOS LOJA*/
CREATE DATABASE LOJA;

/*CONECTAR AO BANCO DE DADOS*/
USE LOJA;

/*VERIFICAR OS STATUS: BANCO DE DADOS CONECTADO*/
STATUS

/*CRIAÇÃO DE TABELAS*/
CREATE TABLE PRODUTO (
IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30),
VALOR FLOAT(10,2)
);

/*CRIAÇÃO DE UM BANCO DE DADOS BACKUP*/
CREATE DATABASE BACKUP;

/*CONECTANDO AO BANCO DE DADOS BACKUP*/
USE BACKUP;

STATUS

/*CRIAÇÃO DE TABELA BKP*/
CREATE TABLE BKP_PRODUTO (
IDBKP INT PRIMARY KEY AUTO_INCREMENT,
IDPRODUTO INT,
NOME VARCHAR(30),
VALOR FLOAT(10,2)
);

/*COMUNICAÇÃO ENTRE BANCOS DE DADOS*/

USE LOJA;

STATUS

/*DENTRO DO DATABASE LOJA, 
VOU INSERIR REGISTRO NO DATABASE BACKUP, 
TABELA BKP_PRODUTO*/
INSERT INTO BACKUP.BKP_PRODUTO VALUES
(NULL,1000,"TESTE",0.0);

-- USAR DATABASE.TABELA NO "INSERT"

/*CONSULTAR SEM MUDAR DE DATABASE*/
SELECT * FROM BACKUP.BKP_PRODUTO;

/*CRIAR TRIGGER EM OUTRA DATABASE*/
