/*MODELAGEM BASICA

ENTIDADES = TABELA
CAMPOS  = ATRIBUTOS*/

CLIENTE

NOME - CARACTER (30)
CPF - NUMERICO (11)
EMAIL - CARACTER (30)
TELEFONE - CARACTER (30)
ENDERECO - CARACTER (100)
SEXO - CARACTER (1)

/*PROCESSOS DE MODELANGEM */

/* FASE 01 E FASE 02  - AD ADM DE DADOS
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LOGICA - QUALQUER PROGRAMA DE MODELAGEM*/

/*FASE 03 - DBA / AD
MODELAGEM FISICA*/

/*INICIANDO A MODELAGEM FISICA*/

/*CRIANDO O BANCO DE DADOS*/

CREATE DATABASE PROJETO; /*CRIAÇÃO DO BANCO DE DADOS PROJETO*/

/*CONECTANDO-SE AO BANCO DE DADOS*/

USE PROJETO;

/*CRIANDO A TABELA CLIENTES*/

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	CPF INT (11),
	EMAIL VARCHAR (30),
	TELEFONE VARCHAR (30),
	ENDERECO VARCHAR (100),
	SEXO CHAR(1)

);

/*VERIFICANDO AS TABELAS DO BANCO*/

SHOW TABLES;

/*VERIFICANDO OS BANCO DE DADOS NO SISTEMA*/

SHOW DATABASES;

/*DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA*/

DESC CLIENTE; 