/*EXERCICIO DE ESTUDO DE TRIGGERS*/

/*CRIAÇÃO DE DATABASE*/

CREATE DATABASE AULA40;

USE AULA40;

/*CRIAÇÃO DE TABELA*/

CREATE TABLE USUARIO (
IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30),
LOGIN VARCHAR(30),
SENHA VARCHAR(100)
);

-- TABELA DE BACKUP
CREATE TABLE BKP_USUARIO(
IDBACKPU INT PRIMARY KEY AUTO_INCREMENT,
IDUSUARIO INT,
NOME VARCHAR(30),
LOGIN VARCHAR(30)
);

/*CRIANDO A TRIGGERS*/

DELIMITE $

-- QUANDO APAGADO OS REGISTROS DA TABELA USUARIO,
-- PEGA OS VALORES ANTIGOS DA TABELA USUARIO E PASSA PARA TABELA BKP_USUARIO

CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
INSERT INTO BKP_USUARIO 
VALUES
(NULL, OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);
END
$

--CONCEITO DE NEW E OLD

DELIMITER ;

/*INSERT - USUARIOS*/

INSERT INTO USUARIO 
VALUES 
(NULL,"ANDRADE","ANDRADE2009","HEXACAMPEAO");

/*CONSULTANDO*/

SELECT * FROM USUARIO;

/*ATIVANDO O TRIGGER*/

DELETE FROM USUARIO
WHERE IDUSUARIO = 1;

/*CONSULTANDO SE O TRIGGER FUNCIONOU E FEZ BACKUP
NA TABELA BKP_USUARIO*/

SELECT * FROM BKP_USUARIO;

+----------+-----------+---------+-------------+
| IDBACKPU | IDUSUARIO | NOME    | LOGIN       |
+----------+-----------+---------+-------------+
|        1 |         1 | ANDRADE | ANDRADE2009 |
+----------+-----------+---------+-------------+
